services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nook-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - nook-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nook-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - nook-network

networks:
  nook-network:
    driver: bridge 