# 言語設定

# 一般的な言語
general = [
    "python",
]

# 特定の言語
specific = [
     "go",
     "rust",
#     "javascript",
#     "typescript",
#     "c",
#     "cpp",
#     "java"
#     "kotlin",
#     "swift",
#     "dart",
#     "ruby",
#     "php",
#     "csharp",
#     "julia"
] 
